// <auto-generated />
using System;
using HrmApi.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HrmApi.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260714050228_AddEntityOrganization")]
    partial class AddEntityOrganization
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HrmApi.Domain.Entities.Organization.BranchEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("CompanyEntityId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GroupSalary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUsingHrm")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CompanyEntityId");

                    b.ToTable("BranchEntities");
                });

            modelBuilder.Entity("HrmApi.Domain.Entities.Organization.CompanyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("CompanyEntityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DayComputeSalary")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Hotline")
                        .HasColumnType("text");

                    b.Property<bool?>("IsComputePrevMonth")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("PrefixFemaleCode")
                        .HasColumnType("text");

                    b.Property<string>("PrefixFullTimeCode")
                        .HasColumnType("text");

                    b.Property<string>("PrefixMaleCode")
                        .HasColumnType("text");

                    b.Property<string>("PrefixPartTimeCode")
                        .HasColumnType("text");

                    b.Property<string>("TaxCode")
                        .HasColumnType("text");

                    b.Property<Guid?>("TimeKeepingStandardId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CompanyEntityId");

                    b.ToTable("CompanyEntities");
                });

            modelBuilder.Entity("HrmApi.Domain.Entities.Organization.DepartmentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BranchEntityId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsNotifyMarketing")
                        .HasColumnType("boolean");

                    b.Property<int>("Limit")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BranchEntityId");

                    b.ToTable("DepartmentEntities");
                });

            modelBuilder.Entity("HrmApi.Domain.Entities.Organization.PartEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("PartMasterEntityId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PartMasterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PartMasterEntityId");

                    b.ToTable("PartEntities");
                });

            modelBuilder.Entity("HrmApi.Domain.Entities.Organization.PartMasterEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BranchEntityId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BranchEntityId");

                    b.ToTable("PartMasterEntities");
                });

            modelBuilder.Entity("HrmApi.Domain.Entities.Organization.PositionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("PartId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PositionMasterEntityId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PositionMasterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PositionMasterEntityId");

                    b.ToTable("PositionEntities");
                });

            modelBuilder.Entity("HrmApi.Domain.Entities.Organization.PositionMasterEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<TimeSpan?>("HourSnapShotEnd")
                        .HasColumnType("interval");

                    b.Property<TimeSpan?>("HourSnapShotStart")
                        .HasColumnType("interval");

                    b.Property<TimeSpan?>("HourWorkingEnd")
                        .HasColumnType("interval");

                    b.Property<TimeSpan?>("HourWorkingStart")
                        .HasColumnType("interval");

                    b.Property<bool>("IsAllowOverTimekeepingStandard")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsApprovedDayOff")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsApprovedWhenHiringCandidate")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsHadASecondInterview")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLimitHoursWorking")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSwapPosition")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTimeKeeping")
                        .HasColumnType("boolean");

                    b.Property<string>("Limit")
                        .HasColumnType("text");

                    b.Property<int?>("MinimumWorkingHour")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PartMasterEntityId")
                        .HasColumnType("uuid");

                    b.Property<int?>("QuantityStandard")
                        .HasColumnType("integer");

                    b.Property<string>("TargetChangePositionIds")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<int?>("WorkingHour")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PartMasterEntityId");

                    b.ToTable("PositionMasterEntities");
                });

            modelBuilder.Entity("HrmApi.Domain.Entities.Organization.BranchEntity", b =>
                {
                    b.HasOne("HrmApi.Domain.Entities.Organization.CompanyEntity", null)
                        .WithMany("Branches")
                        .HasForeignKey("CompanyEntityId");
                });

            modelBuilder.Entity("HrmApi.Domain.Entities.Organization.CompanyEntity", b =>
                {
                    b.HasOne("HrmApi.Domain.Entities.Organization.CompanyEntity", null)
                        .WithMany("ChildCompanies")
                        .HasForeignKey("CompanyEntityId");
                });

            modelBuilder.Entity("HrmApi.Domain.Entities.Organization.DepartmentEntity", b =>
                {
                    b.HasOne("HrmApi.Domain.Entities.Organization.BranchEntity", null)
                        .WithMany("Departments")
                        .HasForeignKey("BranchEntityId");
                });

            modelBuilder.Entity("HrmApi.Domain.Entities.Organization.PartEntity", b =>
                {
                    b.HasOne("HrmApi.Domain.Entities.Organization.PartMasterEntity", null)
                        .WithMany("Parts")
                        .HasForeignKey("PartMasterEntityId");
                });

            modelBuilder.Entity("HrmApi.Domain.Entities.Organization.PartMasterEntity", b =>
                {
                    b.HasOne("HrmApi.Domain.Entities.Organization.BranchEntity", null)
                        .WithMany("PartMasters")
                        .HasForeignKey("BranchEntityId");
                });

            modelBuilder.Entity("HrmApi.Domain.Entities.Organization.PositionEntity", b =>
                {
                    b.HasOne("HrmApi.Domain.Entities.Organization.PositionMasterEntity", null)
                        .WithMany("Positions")
                        .HasForeignKey("PositionMasterEntityId");
                });

            modelBuilder.Entity("HrmApi.Domain.Entities.Organization.PositionMasterEntity", b =>
                {
                    b.HasOne("HrmApi.Domain.Entities.Organization.PartMasterEntity", null)
                        .WithMany("PositionMasters")
                        .HasForeignKey("PartMasterEntityId");
                });

            modelBuilder.Entity("HrmApi.Domain.Entities.Organization.BranchEntity", b =>
                {
                    b.Navigation("Departments");

                    b.Navigation("PartMasters");
                });

            modelBuilder.Entity("HrmApi.Domain.Entities.Organization.CompanyEntity", b =>
                {
                    b.Navigation("Branches");

                    b.Navigation("ChildCompanies");
                });

            modelBuilder.Entity("HrmApi.Domain.Entities.Organization.PartMasterEntity", b =>
                {
                    b.Navigation("Parts");

                    b.Navigation("PositionMasters");
                });

            modelBuilder.Entity("HrmApi.Domain.Entities.Organization.PositionMasterEntity", b =>
                {
                    b.Navigation("Positions");
                });
#pragma warning restore 612, 618
        }
    }
}
